name: Package for Windows

on:
  release:
    types: [published]

jobs:
  build-and-deploy-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # Set up Node.js
    - uses: actions/setup-node@v1
      with:
        node-version: '18.x'
    # Install yarn
    - name: Install Yarn
      run: npm install -g yarn
    # Install dependencies
    - name: Install Dependencies
      run: yarn install
    # Build the project
    - name: Package for Linux
      run: yarn electron:package:linux
    # Upload the release artifact
    - name: Upload Artifacts
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/frame-cast_${{ github.event.release.tag_name }}_amd64.deb